name: slide_image_loader
channels:
  - defaults
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pip:
      - azureml-defaults==1.32.0
      - hi-ml-azure==0.1.9
      - line_profiler==3.3.1
      - monai[all]==0.7.0
