name: image_loader
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.9.18
  - pip:
      - line_profiler==3.3.1
      - monai[all]==0.7.0
      - opencv-python-headless==4.5.4.58
      - simpleitk==1.2.4
