name: image_loader
channels:
  - defaults
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pip:
      - line_profiler==3.3.1
      - monai[all]==0.7.0
      - opencv-python-headless==4.5.4.58
      - simpleitk==1.2.4
