name: multimodal
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip=23.3
  - python=3.9
  - cudatoolkit=11.1
  - pytorch=1.9.0
  - torchvision=0.10.0
  - pip:
    - -r requirements_run.txt
    - -r requirements_test.txt
