name: 'Smoke test environment setup'
description: 'Set up environment for running smoke tests'
runs:
  using: "composite"
  steps:
    - name: create config file
      shell: bash
      run: ./create_config.sh

    - name: Set up Python ${{ env.pythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.pythonVersion }}

    - name: Install required packages
      shell: bash
      run: |
        cd ${{ env.folder }}
        make pip_from_conda

    - name: Install hi-ml locally
      shell: bash
      run: |
        cd hi-ml
        make pip_local

    - name: Install hi-ml-azure locally
      shell: bash
      run: |
        cd hi-ml-azure
        make pip_local
