# This environment definition contains all a basic environment definition that
# is suitable for submitting scripts from the hi-ml-azure folder.
name: himl-azure
dependencies:
  - pip=20.1.1
  - python=3.7.3
