name: 'Download coverage artifacts'
description: 'Download all coverage artifacts'
inputs:
  folder:  # id of input
    description: 'Target folder'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download dot code coverage results
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.folder }}${{ env.HIML_COV_DOT_ARTIFACT_SUFFIX }}
        path: ${{ inputs.folder }}

    - name: Download html code coverage results
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.folder }}${{ env.HIML_COV_HTML_ARTIFACT_SUFFIX }}
        path: ${{ inputs.folder }}/htmlcov

    - name: Download txt code coverage results
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.folder }}${{ env.HIML_COV_TXT_ARTIFACT_SUFFIX }}
        path: ${{ inputs.folder }}

    - name: Download xml code coverage results
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.folder }}${{ env.HIML_COV_XML_ARTIFACT_SUFFIX }}
        path: ${{ inputs.folder }}
