# This is a 'shadow' pipeline designed purely to allow status checks to be run on PRs that use path filtering
name: HI-ML HI-ML-Azure PR Shadow
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "hi-ml-azure/**"
      - "hi-ml/**"
      - ".github/workflows/hi-ml-pr.yml"

jobs:
  hi-ml-pr-completed:
    runs-on: ubuntu-20.04
    steps:
      - name: Final PR Job
        run: |
          echo "Running hi-ml shadow PR job"
