name: Upload Python Package

on:
  release:
    types: [published]

env:
  pythonVersion: 3.7
  PYPI_API_TOKEN: ${{ secrets.HIML_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Python ${{ env.pythonVersion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.pythonVersion }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r run_requirements.txt
          pip install -r test_requirements.txt

    - name: Build package
      run: |
        make clean
        make build
  
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: PYPI_API_TOKEN
